Book/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment')
]

BookStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as orderviews

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('book/', include('Book.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contact/', views.contact, name='contact'),
    path('references/', views.references, name='references'),
    path('category/<int:id>/<slug:slug>/', views.category_books, name='category_books'),
    path('book/<int:id>/<slug:slug>/', views.book_details, name='book_details'),
    path('search/', views.book_search, name='book_search'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

urlpatterns = {
    # ex: /home/
    path('', views.index, name='index'),
}

Book/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.forms import ModelForm
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

class Category(MPTTModel):
    STATUS =(
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(blank=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' >> '.join(full_path[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class Book(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)  # Kategori tablosuyla ilişki kurma
    title = models.CharField(max_length=150)
    author = models.CharField( max_length=30)
    publisher = models.CharField( max_length=30)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField()
    amount = models.IntegerField()
    detail = RichTextUploadingField()
    slug = models.SlugField(blank=True, max_length=150)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class Images(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    title = models.CharField(blank=True, max_length=50)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200, blank=True)
    rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from ckeditor_uploader.fields import RichTextUploadingField
from django.forms import TextInput, Textarea, ModelForm
from django.utils.safestring import mark_safe

class Setting(models.Model):
    STATUS = {
        ('True', 'Evet'),
        ('False', 'Hayır'),
    }
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smptserver = models.CharField(blank=True, max_length=20)
    smptemail = models.CharField(blank=True, max_length=20)
    smptpassword = models.CharField(blank=True, max_length=10)
    smptport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='Images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=20)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True,max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ContactForm(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name'    : TextInput(attrs={'class': 'input', 'placeholder': 'İsim & Soyisim'}),
            'subject' : TextInput(attrs={'class': 'input', 'placeholder': 'Konu'}),
            'email'   : TextInput(attrs={'class': 'input', 'placeholder': 'Email Adres'}),
            'message' : Textarea(attrs={'class': 'input', 'placeholder': 'Mesajınız', 'rows': '5'}),
        }

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/', default='images/users/user.png')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' [' + self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='Kullanıcı Adı')
    email = forms.EmailField(max_length=200, label='Email')
    first_name = forms.CharField(max_length=100, help_text='Adınız', label='Adı')
    last_name = forms.CharField(max_length=100, help_text='Soyadınız', label='Soyadı')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)

Book/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from Book.models import Comment, CommentForm

def index(request):
    return HttpResponse("Book Page")

@login_required(login_url='/login') #Check Login
def addcomment(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    if request.method == 'POST':   #form post edildiyse
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user = request.user     #Access User Session Information

            data = Comment()   #model ile bağlantı kur
            data.user_id = current_user.id
            data.book_id = id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip = request.META.get('REMOTE_ADDR') #Client computer ip address
            data.save() #veritabanına kaydet
            messages.success(request, "Yorumunuz başarı ile gönderilmiştir. Teşekkür ederiz")

            return HttpResponseRedirect(url)

    messages.warning(request, "Yorumunuz kaydedilmedi lütfen kontrol ediniz")
    return HttpResponseRedirect(url)

home/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
# Create your views here.
from Book.models import Book, Category, Images, Comment
from home.forms import SearchForm, SignUpForm
from home.models import Setting, ContactForm, ContactFormMessage, UserProfile
from order.models import ShopCart

def index (request):
    current_user = request.user
    setting = Setting.objects.get(pk=1)
    sliderdata = Book.objects.all()
    latestdata = Book.objects.all().order_by('-id')[:6]
    randomdata = Book.objects.all().order_by('?')
    bestrateddata = Book.objects.all()[:6]
    category = Category.objects.all()
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()  # count item in shop cart
    context = {'setting': setting,
               'page': 'home',
               'sliderdata': sliderdata,
               'category': category,
               'latestdata': latestdata,
               'randomdata': randomdata,
               'bestrateddata': bestrateddata}
    return render(request, 'index.html', context)

def aboutus(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    context = {'setting': setting, 'page': 'aboutus', 'category': category}
    return render(request, 'aboutus.html', context)

def contact(request):
    if request.method == 'POST':   # form post edildiyse
        form = ContactForm(request.POST)
        if form.is_valid():
            data = ContactFormMessage()  # model ile bağlantı kur
            data.name = form.cleaned_data['name']  # formdan bilgiyi al
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()  # veritabanına kaydet
            messages.success(request, "Mesajınız başarı ile gönderilmiştir. Teşekkür ederiz")
            return HttpResponseRedirect('/contact')

    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    form = ContactForm()
    context = {'setting': setting, 'page': 'contact', 'form': form, 'category': category}
    return render(request, 'contact.html', context)

def references(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    context = {'setting': setting, 'page': 'references', 'category': category}
    return render(request, 'references.html', context)

def category_books(request,id,slug):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    categorydata = Category.objects.get(pk=id)
    books = Book.objects.filter(category_id=id)
    context = {
        'setting': setting,
        'books': books,
        'page': 'books',
        'category': category,
        'categorydata': categorydata
    }
    return render(request, 'books.html', context)

def book_details(request, id ,slug):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    book = Book.objects.get(pk=id)
    images = Images.objects.filter(book_id=id)
    comments = Comment.objects.filter(book_id=id, status='True')
    context = {
        'setting': setting,
        'page': 'book_details',
        'book': book,
        'category': category,
        'images': images,
        'comments': comments,
    }
    return render(request, 'book_details.html', context)

def book_search(request):
    if request.method == 'POST':     # form post edildiyse
        form = SearchForm(request.POST)
        if form.is_valid():
            setting = Setting.objects.get(pk=1)
            category = Category.objects.all()
            query = form.cleaned_data['query']     # formdan bilgiyi al
            books = Book.objects.filter(title__icontains=query)   # Select * from Book where title like %query%
            context = {
                'setting': setting,
                'page': 'book_search',
                'books': books,
                'category': category,
            }
            return render(request, 'book_search.html', context)

    return HttpResponseRedirect('/')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            #Redirect to a success page
            messages.success(request, "Hoş Geldiniz..")
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, "Giriş Hatası! Kullanıcı adı ya da şifre yanlış")
            return HttpResponseRedirect('/login')

    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    context = {
        'setting': setting,
        'page': 'login',
        'category': category,
    }
    return render(request, 'login.html', context)

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)

            # create data in profile table for user
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.save()
            messages.success(request, "Hoş geldiniz..")
            return HttpResponseRedirect('/')

    form = SignUpForm()
    category = Category.objects.all()
    setting = Setting.objects.get(pk=1)
    context = {
        'setting': setting,
        'page': 'signup',
        'category': category,
        'form': form,
    }

    return render(request, 'signup.html', context)

home/templates/aboutus.html
{% extends "homebase.html" %}
{% load static %}
{% block title %} {{ setting.title }} {% endblock %}
{% block keywords %} {{ setting.keywords}} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}


{% block content %}
    <!-- BREADCRUMB -->
    <div id = "breadcrumb">
        <div class ="container">
            <ul class ="breadcrumb-item">
                <li><a href="/">Anasayfa</a></li>
                <li class="active">/ Hakkımızda</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->

    <!-- Single Blog Post -->

    <div class="single_post">
        <div class="container">
            <div class="row">

                <div class="col-lg-8 offset-lg-2">
                    <div class="single_post_quote text-center">
                        {{ setting.aboutus | safe }}
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

home/templates/book_details.html
{% extends "homebase.html" %}
{% load static %}
{% block title %} {{ book.title }}{% endblock %}
{% block keywords %} {{ book.keywords}} {% endblock %}
{% block description %} {{ book.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}

{% block content %}
    <!-- BREADCRUMB -->
    <div id = "breadcrumb">
        <div class ="container">
            <ul class ="breadcrumb-item">
                <li><a href="/">Anasayfa</a></li>
                <li class="active">/ {{ book.title}}</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- Single Product -->

    <div class="single_product">
        <div class="container">
            <div class="row">

                <!-- Images -->
                <div class="col-lg-2 order-lg-1 order-2">
                    {% for rs in images %}
                        <ul class="image_list">
                            <li><img src="{{ rs.image.url}}" alt=""></li>
                        </ul>
                    {% endfor %}
                </div>

                <!-- Selected Image -->
                <div class="col-lg-5 order-lg-2 order-1">
                    <div class="image_selected"><img src="{{ book.image.url }}" alt=""></div>
                </div>

                <!-- Description -->
                <div class="col-lg-5 order-3">
                    <div class="product_description">
                        <div class="product_category">{{ book.category }}</div>
                        <div class="product_name">{{ book.title}}</div>
                        <div class="product_category">{{ book.author }}</div>
                        <div class="rating_r rating_r_4 product_rating"><i></i><i></i><i></i><i></i><i></i></div>
                        <div class="product_text"><p>{{ book.description | safe }}</p></div>
                        <div class="order_info d-flex flex-row">
                            <form action="/order/addtocart/{{ book.id }}" method="post">
                                {% csrf_token %}
                                <div class="clearfix" style="z-index: 1000;">

                                    <!-- Product Quantity -->
                                    <div class="product_quantity clearfix">
                                        <span>Adet: </span>
                                        <input name="quantity" class="input" type="number" min="0" max="{{ book.amount }}" value="1">
                                        <div class="quantity_buttons">
                                            <div id="quantity_inc_button" class="quantity_inc quantity_control"><i class="fas fa-chevron-up"></i></div>
                                            <div id="quantity_dec_button" class="quantity_dec quantity_control"><i class="fas fa-chevron-down"></i></div>
                                        </div>
                                    </div>

                                </div>

                                <div class="product_price">₺{{ book.price }}</div>
                                <div class="button_container">
                                    <button type="button" class="button cart_button"><a href="/order/addtocart/{{ book.id }}">Sepete Ekle</a></button>
                                    <div class="product_fav"><i class="fas fa-heart"></i></div>
                                </div>


                            </form>
                        </div>
                    </div>
                </div>

                <!-- Comments -->
                <div class="col-lg-12 order-12">
                    <div class="product__details__tab">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab"
                                   aria-selected="true">Detay</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab"
                                   aria-selected="false">Yorumlar</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <div class="product__details__tab__desc">
                                    <p>{{ book.detail | safe }}</p>
                                </div>
                            </div>
                            <div class="tab-pane" id="tabs-2" role="tabpanel">

                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="product-reviews">
                                            {% for rs in comments %}
                                                <div class="single-review">
                                                    <div class="review-heading">
                                                        <a href="#"><i class="fa fa-user-o"></i> <b>{{ rs.user.first_name }}</b></a>
                                                        <a href="#"><i class="fa fa-clock-o"></i> {{ rs.create_at }}</a>
                                                        <div class="review-rating pull-right">
                                                            <i class="fa fa-star{% if rs.rate < 1 %}-o empty{% endif %}"></i>
                                                            <i class="fa fa-star{% if rs.rate < 2 %}-o empty{% endif %}"></i>
                                                            <i class="fa fa-star{% if rs.rate < 3 %}-o empty{% endif %}"></i>
                                                            <i class="fa fa-star{% if rs.rate < 4 %}-o empty{% endif %}"></i>
                                                            <i class="fa fa-star{% if rs.rate < 5 %}-o empty{% endif %}"></i>
                                                        </div>
                                                    </div>
                                                    <div class="review-body">
                                                        <b>{{ rs.subject }}</b>
                                                        <p>{{ rs.comment }}</p>
                                                    </div>
                                                </div>
                                            {% endfor %}

                                            <div class="col-lg-12">
                                                <div class="product__pagination blog__pagination">
                                                    <a class="active">1</a>
                                                    <a href="#">2</a>
                                                    <a href="#">3</a>
                                                    <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <h4 class="text-uppercase">Yorumunuzu Paylaşın</h4>
                                        <p>Email adresiniz paylaşılmayacaktır.</p>

                                        <form class="review-form" action="/book/addcomment/{{ book.id }}" method="post">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input class="input" type="text" name="subject" id="id_subject" placeholder="Konu"/>
                                            </div>

                                            <div class="form-group">
                                                <textarea class="input" name="comment" id="id_comment" placeholder="Yorumunuz"></textarea>
                                            </div>

                                            <div class="form-group">
                                                <div class="input-rating">
                                                    <strong class="text-uppercase">Derecelendirmeniz: </strong>
                                                    <div class="stars">
                                                        <input type="radio" id="star5" name="rate" value="5" /><label for="star5"></label>
                                                        <input type="radio" id="star4" name="rate" value="4" /><label for="star4"></label>
                                                        <input type="radio" id="star3" name="rate" value="3" /><label for="star3"></label>
                                                        <input type="radio" id="star2" name="rate" value="2" /><label for="star2"></label>
                                                        <input type="radio" id="star1" name="rate" value="1" /><label for="star1"></label>
                                                    </div>
                                                </div>
                                            </div>

                                            {% if user.id is not None %}
                                                <button class="button cart_button">Yorum Yap</button>
                                            {% else %}
                                                Yorum eklemek için <a href="/login">Login</a> olunuz!
                                            {% endif %}

                                        </form>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

home/templates/book_search.html
{% extends "homebase.html" %}
{% load static %}
{% block title %} Kitap Arama Sonuçları {% endblock %}
{% block keywords %} {{ categorydata.keywords }} {% endblock %}
{% block description %} {{ categorydata.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}

{% block content %}
    <!-- BREADCRUMB -->
    <div id = "breadcrumb">
        <div class ="container">
            <ul class ="breadcrumb-item">
                <li><a href="/">Anasayfa</a></li>
                <li class="active">/ Arama Sonuçları</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <table cellpadding="3" width="1200">
                    <tr>
                        <th>Resim</th>
                        <th>Kitap Adı</th>
                        <th>Kategori</th>
                        <th>Fiyat</th>
                    </tr>
                    {% for rs in books %}
                        <tr>
                            <td width="300" height="300"> <a href="/book/{{ rs.id }}/{{ rs.slug }}"><img src="{{ rs.image.url }}" style="height: 250px" alt=""></a> </td>
                            <td> <h4 class="product_name"><a href="/book/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a></h4></td>
                            <td> <a href="/category/{{ rs.category.id }}/{{ rs.category.slug }}">{{ rs.category }}</a> </td>
                            <td> <h4>${{ rs.price }}</h4></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->
{% endblock %}

home/templates/index.html
{% extends "homebase.html" %}

{% block title %} {{ setting.title }} {% endblock %}
{% block keywords %} {{ setting.keywords}} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}

{% block slider %}
    {% include "slider.html" %}
{% endblock %}

{% block content %}
    {% include "content.html" %}
{% endblock %}

home/templates/references.html
{% extends "homebase.html" %}

{% block title %} {{ setting.title }} {% endblock %}
{% block keywords %} {{ setting.keywords}} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}

{% block content %}
    <!-- BREADCRUMB -->
    <div id = "breadcrumb">
        <div class ="container">
            <ul class ="breadcrumb-item">
                <li><a href="/">Anasayfa</a></li>
                <li class="active">/ Referanslar</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->

    <!-- Single Blog Post -->

    <div class="single_post">
        <div class="container">
            <div class="row">

                <div class="col-lg-8 offset-lg-2">
                    <div class="single_post_quote text-center">
                        {{ setting.references | safe }}
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}